
Insert into BOOKS_ADMIN.CUSTOMER (ACC_NO,BALANCE,NAME) values (CUSTOMER_SEQUENCE.nextval,1000,'Navin');
Insert into BOOKS_ADMIN.CUSTOMER (ACC_NO,BALANCE,NAME) values (CUSTOMER_SEQUENCE.nextval,1000,'Vinod');
